spring:
  h2:
    console:
      enabled: true
      path: /h2
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      table-name: SPRING_SESSION
    timeout: 60000

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
